### ISSUE TITLE
Package doesn't install, maybe corrupt

### ISSUE THREAD

**Issue by RussellGrayxd** [RS-eco/rasterSp#2]
Trying to install the package using the code provided on the git page yields an error on the "creating vignettes" line

E  creating vignettes (2m 27.7s)
   --- re-building 'iucn-invasions.Rmd' using rmarkdown
   Quitting from lines 22-28 (iucn-invasions.Rmd) 
   Error: processing vignette 'iucn-invasions.Rmd' failed with diagnostics:
   length(dsn) == 1L is not TRUE
   --- failed re-building 'iucn-invasions.Rmd'
   
   SUMMARY: processing the following file failed:
     'iucn-invasions.Rmd'
   
   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'rasterSp' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Quitting from lines 22-28 (iucn-invasions.Rmd) 
E> Error: processing vignette 'iucn-invasions.Rmd' failed with diagnostics:
E> length(dsn) == 1L is not TRUE
E> --- failed re-building 'iucn-invasions.Rmd'
E> 
E> SUMMARY: processing the following file failed:
E>   'iucn-invasions.Rmd'
E> 
E> Error: Vignette re-building failed.
E> Execution halted

**Comment by fabro** [comment]
I had the same issue (below). I'm using:
R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

Previously, I updated the rmarkdown and remotes packages, but this didn't help. 


ISSUE:
...
E  creating vignettes (44.6s)
   --- re-building ‘iucn-invasions.Rmd’ using rmarkdown
   Error: processing vignette 'iucn-invasions.Rmd' failed with diagnostics:
   The 'rmarkdown' package should be declared as a dependency of the 'rasterSp' package (e.g., in the  'Suggests' field of DESCRIPTION), because the latter contains vignette(s) built with the 'rmarkdown' package. Please see https://github.com/yihui/knitr/issues/1864 for more information.
   --- failed re-building ‘iucn-invasions.Rmd’
   
   SUMMARY: processing the following file failed:
     ‘iucn-invasions.Rmd’
   
   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'rasterSp' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> --- re-building ‘iucn-invasions.Rmd’ using rmarkdown
E> Error: processing vignette 'iucn-invasions.Rmd' failed with diagnostics:
E> The 'rmarkdown' package should be declared as a dependency of the 'rasterSp' package (e.g., in the  'Suggests' field of DESCRIPTION), because the latter contains vignette(s) built with the 'rmarkdown' package. Please see https://github.com/yihui/knitr/issues/1864 for more information.
E> --- failed re-building ‘iucn-invasions.Rmd’
E> 
E> SUMMARY: processing the following file failed:
E>   ‘iucn-invasions.Rmd’
E> 
E> Error: Vignette re-building failed.
E> Execution halted

**Comment by fabro** [comment]
thanks to @JesusNPL suggestion, I could installed it without requiring the vignettes to be built:

remotes::install_github("RS-eco/rasterSp", build_vignettes = FALSE)
